### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by errantSquam** [KimmyKitsuragi/supreme-picross-engine#3]
Basic Functionality
- [ ] Validation checking when player has completed Picross
  - [ ] Either a congratulations message or pop-up 

Pre-Set Pages
- [ ] Tutorial page with bonus explanations + basic picross (should the explanations be in a modal?)
- [ ] Archive of previous puzzles

Custom Picross
- [ ] Enable add/delete columns for custom Picross
- [ ] Export/share link feature 
  - [ ] Maybe even import?! Import an existing share link and continue tinkering with it
- [ ] Color Picross. Add/remove colors to palette
  - [ ] Possibly even color picker?!
  - [ ] May need a fill tool...I dunno what the algorithm for that is like, though. Gotta look into it
 
Daily Puzzle
- [ ] Export list of 1bit art and convert to picross format. Grab CC stuff from itch.io
  - [ ] Also credit artists!! Extremely important!!
- [ ] Checker to swap daily puzzle on client side

Misc.
- [ ] Rive based mascot...thing...that reacts to how complete your puzzle is (i propose an utyaduckcore duck)
- [ ] Optional timer? Maybe have it run in the background but players have an option to toggle it on/off because watching how long you take on a puzzle might be stressful for people
- [ ] Share score I guess. Sorry for social media slop
- [ ] Maybe a daily puzzle submission function. Possibly off-site because we're too broke for a server. May need to gatekeep with $$. Once again, sorry for monetization slop
