### ISSUE TITLE
Validation To-Do

### ISSUE THREAD

**Issue by KimmyKitsuragi** [KimmyKitsuragi/supreme-picross-engine#4]
- [x] Block all interaction with canvas when finished
- [x] Pop up congratulations modal ? We can leave this as a component so all the future social media sharing stuff can go in here
- [x] Once modal is quit the canvas is still uninteractable till the user hits the clear button
