### ISSUE TITLE
Custom Picross Builder TODO

### ISSUE THREAD

**Issue by KimmyKitsuragi** [KimmyKitsuragi/supreme-picross-engine#5]
- [x] Create new page -> route ?
- [x] Set dimensions through a form on the left
- [x] canvas more or less the same, user inputs solution with the same tools
- [x] Ability to add row/col constraints as form inputs
- [x] new button to save puzzle
- [x] function to encode puzzle as binary
